baseURL: 'https://vittseva.com'
languageCode: 'en-us'
title: 'VittSeva - Financial Services'
theme: 'your-theme-name'

params:
  description: 'Complete financial services including investment advisory, insurance solutions, loan assistance, and tax planning'
  author: 'VittSeva Team'

menu:
  main:
    - name: 'Services'
      url: '#services'
      weight: 1
    - name: 'About'
      url: '#about'
      weight: 2
    - name: 'Testimonials'
      url: '#testimonials'
      weight: 3
    - name: 'Contact'
      url: '#contact'
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true